### PR TITLE
Add Range.setHyperlink sample and remove errant yml files

### PR DESCRIPTION
**Pull request by AlexJerabek**
The yml files appear to have been accidentally added in an previous direct-commit to master.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[b5db0de](https://github.com/OfficeDev/office-scripts-docs-reference/commits/b5db0deaa49d7bf8f2999b0f87f02bf09b77cc44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/code-snippets/excel-snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/code-snippets/excel-snippets.yaml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/BoundingBox.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/BoundingBox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/Map.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/Map.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/index.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/index.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/toc.yml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel/snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/generate-docs/json/excel/snippets.yaml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C3%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C202008031736115432-57%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5lMqfbCQHPX9okwKYTo8o79rzfSwvkjLtNxr8yi8pn4%3D&st=2020-08-03T17%3A34%3A32Z&se=2020-09-03T17%3A39%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b7e1f975-26d5-fb7f-b635-d5c5bc9f9be0?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[bbac9c0](https://github.com/OfficeDev/office-scripts-docs-reference/commits/bbac9c04a143c3a68586107d8f9669d621a2f1d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/code-snippets/excel-snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/code-snippets/excel-snippets.yaml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/BoundingBox.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/BoundingBox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/Map.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/Map.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/index.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/index.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/toc.yml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel/snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/generate-docs/json/excel/snippets.yaml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C3%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C202008032321161942-57%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KkNdn4nmKlLQFUjcmxYqWxU%2BjKw1xftfv4I5oKkIjMo%3D&st=2020-08-03T23%3A19%3A28Z&se=2020-09-03T23%3A24%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b7e1f975-26d5-fb7f-b635-d5c5bc9f9be0?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AlexJerabek** [comment]
Added an additional sample that's going into the office-scripts-docs repo. It's a basic sample that uses `getFormula` and `setFormula`.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[e8f8672](https://github.com/OfficeDev/office-scripts-docs-reference/commits/e8f8672efcfb8998410677aab2e432eef7baf0a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/code-snippets/excel-snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/code-snippets/excel-snippets.yaml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/BoundingBox.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/BoundingBox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/Map.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/Map.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/index.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/index.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/toc.yml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel/snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/generate-docs/json/excel/snippets.yaml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C4%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C202008042045381886-57%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZVeRD2SWPOEtcQq6rmNMBgIJVC%2BJxEf1D7p2tXqMCso%3D&st=2020-08-04T20%3A43%3A43Z&se=2020-09-04T20%3A48%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b7e1f975-26d5-fb7f-b635-d5c5bc9f9be0?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[3f3ca1d](https://github.com/OfficeDev/office-scripts-docs-reference/commits/3f3ca1dec26dbb2bdd0e16cd6e1e917493fb0d9a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/code-snippets/excel-snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/code-snippets/excel-snippets.yaml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/BoundingBox.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/BoundingBox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/Map.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/Map.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/index.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/index.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/toc.yml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel/snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/generate-docs/json/excel/snippets.yaml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C11%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C202008112105504968-57%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sqVRj%2BMu%2FwDcPY%2Bg2pz7lAHARqbONpPTKUvLFTdFX1U%3D&st=2020-08-11T21%3A04%3A13Z&se=2020-09-11T21%3A09%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b7e1f975-26d5-fb7f-b635-d5c5bc9f9be0?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[8f46b9f](https://github.com/OfficeDev/office-scripts-docs-reference/commits/8f46b9fa716fe2ea1390865888602d86c8e1f11a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/code-snippets/excel-snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/code-snippets/excel-snippets.yaml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/BoundingBox.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/BoundingBox.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/Map.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/Map.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/excel/excelscript/excelscript.range.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/index.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/index.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/docs/docs-ref-autogen/toc.yml) | :white_check_mark:Succeeded | |
[generate-docs/json/excel/snippets.yaml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Sample/generate-docs/json/excel/snippets.yaml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C8%5C11%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C202008112108151510-57%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=So9R4RYu7qYrfVvDVHgEOGpnoZJpD1fJL4oIqdtpPyY%3D&st=2020-08-11T21%3A07%3A46Z&se=2020-09-11T21%3A12%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/b7e1f975-26d5-fb7f-b635-d5c5bc9f9be0?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
