### PR TITLE
Redo overview file

### PR DESCRIPTION
**Pull request by AlexJerabek**
This address #5 by providing a basic object model with links.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[39aee12](https://github.com/OfficeDev/office-scripts-docs-reference/commits/39aee1257e259b1a2a3b6c67af6ad8fa7d50f8b0)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[39aee12](https://github.com/OfficeDev/office-scripts-docs-reference/commits/39aee1257e259b1a2a3b6c67af6ad8fa7d50f8b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/office-scripts/overview.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C12%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C201912122050499056-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6crPChVm6ub8g1P9N37R7kpcUqwQdw%2F5Z%2BZFAKKszT0%3D&st=2019-12-12T20%3A48%3A48Z&se=2020-01-12T20%3A53%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[265d864](https://github.com/OfficeDev/office-scripts-docs-reference/commits/265d864f182e1350658bfb132673aa543c3e9b66)_: 

:clock10: **Pending**: waiting for processors ([18](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[265d864](https://github.com/OfficeDev/office-scripts-docs-reference/commits/265d864f182e1350658bfb132673aa543c3e9b66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel-scripts/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/toc.yml) | :warning:Warning | | [Details](#user-content-908adbae-e7755b3e)
[docs/docs-ref-autogen/excel-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/office-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/overview.md) | :white_check_mark:Succeeded | |
[generate-docs/scripts/postprocessor.ts](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/generate-docs/scripts/postprocessor.ts) | :white_check_mark:Succeeded | |

<a id="908adbae-e7755b3e"></a>
### [docs/docs-ref-autogen/excel-scripts/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/toc.yml)
 - **Line 0**: **[Warning]** `````Invalid file link:(~/docs-ref-autogen/excel-scripts/overview.md).`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C12%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C201912122331487098-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eApisrzgJfqkMR2eREou53EPJcXSUcag%2FUczK3XjeLE%3D&st=2019-12-12T23%3A29%3A46Z&se=2020-01-12T23%3A34%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[d371f56](https://github.com/OfficeDev/office-scripts-docs-reference/commits/d371f5638d18161298a8946d2608908cf2400f1f)_: 

:clock10: **Pending**: waiting for processors ([17](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 17 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[3ce6fe0](https://github.com/OfficeDev/office-scripts-docs-reference/commits/3ce6fe0e9b55ea3b70f7b8fa05ef4e0becc1f439)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[9c77eec](https://github.com/OfficeDev/office-scripts-docs-reference/commits/9c77eec0fa305946b15304d33b5f2d904de6d109)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[3ce6fe0](https://github.com/OfficeDev/office-scripts-docs-reference/commits/3ce6fe0e9b55ea3b70f7b8fa05ef4e0becc1f439)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel-scripts/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/office-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/overview.md) | :white_check_mark:Succeeded | |
[generate-docs/scripts/postprocessor.ts](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/generate-docs/scripts/postprocessor.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C12%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C201912122348353071-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4I0AR4RsmiDngrxkWDTln9JscMVji%2FSYVeBgpMpYH0E%3D&st=2019-12-12T23%3A46%3A30Z&se=2020-01-12T23%3A51%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[63caa41](https://github.com/OfficeDev/office-scripts-docs-reference/commits/63caa41bb9fa6c9f50399e47f0d9a03894cd77fa)_: 

:clock10: **Pending**: waiting for processors ([16](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 16 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[9c77eec](https://github.com/OfficeDev/office-scripts-docs-reference/commits/9c77eec0fa305946b15304d33b5f2d904de6d109)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel-scripts/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/office-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/overview.md) | :white_check_mark:Succeeded | |
[generate-docs/scripts/postprocessor.ts](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/generate-docs/scripts/postprocessor.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C12%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C201912122348437634-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GowO7p%2BHGD9mF3EZAmSyeWpGvq8CjrRXZFtB0%2B8Tce4%3D&st=2019-12-12T23%3A49%3A42Z&se=2020-01-12T23%3A54%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[63caa41](https://github.com/OfficeDev/office-scripts-docs-reference/commits/63caa41bb9fa6c9f50399e47f0d9a03894cd77fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/docs-ref-autogen/excel-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/excel-scripts/toc.yml](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/excel-scripts/toc.yml) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/office-scripts/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/office-scripts/overview.md) | :white_check_mark:Succeeded | |
[docs/docs-ref-autogen/overview.md](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/docs/docs-ref-autogen/overview.md) | :white_check_mark:Succeeded | |
[generate-docs/scripts/postprocessor.ts](https://github.com/OfficeDev/office-scripts-docs-reference/blob/AlexJ-Overview/generate-docs/scripts/postprocessor.ts) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C12%5Cb7e1f975-26d5-fb7f-b635-d5c5bc9f9be0%5CPullRequest%5C201912122351477496-13%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Wdl7gU5UCLYLD6hywMkqjyoLb9M1Ec6sygXf6PGKTR4%3D&st=2019-12-12T23%3A51%3A49Z&se=2020-01-12T23%3A56%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by AlexJerabek** [comment]
Checking in to prepare for going live. Please continue to leave any feedback here or as a new issue.

**Pull request merged**
